# Keep GitHub Actions dependencies current. The release workflow
# holds the signing, notarization, Sparkle, and license secrets, so the actions
# it runs are supply-chain-sensitive). Dependabot proposes bumps as PRs that run
# the full CI gate before merging; it also keeps commit-SHA pins fresh once the
# `uses:` references stay pinned to immutable commit SHAs.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
      day: monday
    groups:
      site-dependencies:
        patterns: ["*"]
